import type { NextPage } from 'next';
import Head from 'next/head';
import {Header, Footer, ContactForm} from '../components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Pyen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
        <ContactForm/>
      </main>
      <Footer/>
    </div>
  )
}

export default Home;
