import type { NextPage } from 'next';
import Head from 'next/head';
import classes from '../styles/Home.module.scss';
import {Header} from '../components';

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Pyen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header/>
      </main>
    </div>
  )
}

export default Home;
